### ISSUE TITLE
brew update or upgade: warnings due to camel case

### ISSUE THREAD

**Issue by didier-durand** [knative/homebrew-client#19]
When running brew upgrade or brew update, the pairs of warnings below are emitted by the brew command for both update and upgrade. They are due to different spelling fileutils vs FileUtils. See messages below.

I initially opened [https://github.com/Homebrew/brew/issues/10883](https://github.com/Homebrew/brew/issues/10883)

The homebrew team analyzed the issue and figured out that the issue was very probably on the side of the knative client. Please, see the final part of the ticket to see how they got there by analyzing your Ruby code.

Let me know if more info is needed.

Best,

Didier

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/FileUtils.rb:1267: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/FileUtils.rb:1540: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1540: warning: previous definition of DIRECTORY_TERM was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/FileUtils.rb:1542: warning: already initialized constant FileUtils::Entry_::SYSCASE
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1542: warning: previous definition of SYSCASE was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/FileUtils.rb:1595: warning: already initialized constant FileUtils::OPT_TABLE
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1595: warning: previous definition of OPT_TABLE was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/FileUtils.rb:1649: warning: already initialized constant FileUtils::LOW_METHODS
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1649: warning: previous definition of LOW_METHODS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/FileUtils.rb:1656: warning: already initialized constant FileUtils::METHODS
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1656: warning: previous definition of METHODS was here
```

**Comment by AlexandreRoba** [comment]
Same here. I ended up removing **kn** for the time being.

**Comment by navidshaikh** [comment]
/reopen

@didier-durand @AlexandraRoatis : can you please quick give this another try and see if the warnings are gone ?

**Comment by didier-durand** [comment]
@navidshaikh : I just tried and it's fine for me. Now, the previous messages have disappeared when I do `brew upgrade`. So, all good! Thanks. Didier

**Comment by navidshaikh** [comment]
cool! thanks for confirming @didier-durand!

>  I ended up removing kn for the time being.

@AlexandreRoba : the warnings are fixed, can you please try again? :-)

/close

feel free to reopen it if you find any issues.

**Comment by drnic** [comment]
I had to uninstall `kn` to make the warnings go away.

**Comment by navidshaikh** [comment]
> I had to uninstall kn to make the warnings go away.

@drnic : I think default `master`-->`main` branch change is hitting here? There are no more refs present for `master` branch anymore, see https://github.com/knative/homebrew-client/pull/24. The suggestion in PR is to untap the local repo completely and start afresh. Can you give this a try ?

**Comment by drnic** [comment]
@navidshaikh thanks, yes that must be it. I removed + re-added the tap. No more warnings.
